// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using brgy_mgmt_dotnet.identity.Contexts;

#nullable disable

namespace brgy_mgmt_dotnet.identity.Migrations
{
    [DbContext(typeof(BrgyIdentityDbContext))]
    [Migration("20240223114541_addClaims")]
    partial class addClaims
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("brgy_mgmt_dotnet.identity.Models.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("96445f78-7f86-4a0f-8e46-44ecf3690a47"),
                            Description = "Administrator",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = new Guid("de0484d9-1201-4298-bc5d-ae1ca3392556"),
                            Description = "Officer One",
                            Name = "Officer One",
                            NormalizedName = "OFFICER ONE"
                        },
                        new
                        {
                            Id = new Guid("b0954a50-4a88-44b1-9f80-09ca191307f4"),
                            Description = "Officer Two",
                            Name = "Officer Two",
                            NormalizedName = "OFFICER TWO"
                        });
                });

            modelBuilder.Entity("brgy_mgmt_dotnet.identity.Models.AppRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "Administrator_Role_Claim",
                            ClaimValue = "Administrator Role Claim",
                            RoleId = new Guid("96445f78-7f86-4a0f-8e46-44ecf3690a47")
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "Officer_One_Claim",
                            ClaimValue = "Officer One Role Claim",
                            RoleId = new Guid("de0484d9-1201-4298-bc5d-ae1ca3392556")
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "Officer_Two_Claim",
                            ClaimValue = "Officer Two Role Claim",
                            RoleId = new Guid("b0954a50-4a88-44b1-9f80-09ca191307f4")
                        });
                });

            modelBuilder.Entity("brgy_mgmt_dotnet.identity.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomUsername")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("ExternalUserId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ed72e4b-d489-4c2a-9f9a-a8a29e8ef735"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "91b3d50f-214e-48d2-af48-685601d0f112",
                            CustomUsername = "admin",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJyVHCzH6ZE+Gqnny9LxRICf55zgI4iYYBENvqwxh4uF08rbO1coZCZTIG884S8Ktw==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        },
                        new
                        {
                            Id = new Guid("76361a7e-0f21-4eea-8681-a3ce26588b19"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "da9cce76-f5dd-4258-b4d7-dd2e650ab785",
                            CustomUsername = "ggn",
                            Email = "garyn.green@localhost.com",
                            EmailConfirmed = true,
                            ExternalUserId = 1,
                            LockoutEnabled = false,
                            NormalizedEmail = "GARYN.GREEN@LOCALHOST.COM",
                            NormalizedUserName = "GARYN.GREEN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELHNd0SE8Ofd448Fy62UypBMQzrUa9Uzr7khMowGFO91cu9mRDm25LGJOb6UDy+sIg==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "garyn.green@localhost.com"
                        },
                        new
                        {
                            Id = new Guid("f063d4f6-34f2-4169-b01c-da053928fa2a"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4ad1da05-5e06-4fc4-8c3d-235c13218802",
                            CustomUsername = "jss",
                            Email = "jamesina.sanders@localhost.com",
                            EmailConfirmed = true,
                            ExternalUserId = 2,
                            LockoutEnabled = false,
                            NormalizedEmail = "JAMESINA.SANDERS@LOCALHOST.COM",
                            NormalizedUserName = "JAMESINA.SANDERS@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELz5SNI/7JNvpKUyVJqeR3GVk4ZI8MhY37IRgy9WajoJFDumKYwdNL5ddCaGE048Hw==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "jamesina.sanders@localhost.com"
                        });
                });

            modelBuilder.Entity("brgy_mgmt_dotnet.identity.Models.AppUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "Administrator_User_Claim",
                            ClaimValue = "Administrator User Claim",
                            UserId = new Guid("1ed72e4b-d489-4c2a-9f9a-a8a29e8ef735")
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "Garyn_Claim",
                            ClaimValue = "Garyn One",
                            UserId = new Guid("76361a7e-0f21-4eea-8681-a3ce26588b19")
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "Jamesina_Claim",
                            ClaimValue = "Jamesina Two",
                            UserId = new Guid("f063d4f6-34f2-4169-b01c-da053928fa2a")
                        });
                });

            modelBuilder.Entity("brgy_mgmt_dotnet.identity.Models.AppUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("1ed72e4b-d489-4c2a-9f9a-a8a29e8ef735"),
                            RoleId = new Guid("96445f78-7f86-4a0f-8e46-44ecf3690a47")
                        },
                        new
                        {
                            UserId = new Guid("76361a7e-0f21-4eea-8681-a3ce26588b19"),
                            RoleId = new Guid("de0484d9-1201-4298-bc5d-ae1ca3392556")
                        },
                        new
                        {
                            UserId = new Guid("f063d4f6-34f2-4169-b01c-da053928fa2a"),
                            RoleId = new Guid("b0954a50-4a88-44b1-9f80-09ca191307f4")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("brgy_mgmt_dotnet.identity.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("brgy_mgmt_dotnet.identity.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("brgy_mgmt_dotnet.identity.Models.AppRoleClaim", b =>
                {
                    b.HasOne("brgy_mgmt_dotnet.identity.Models.AppRole", "AppRole")
                        .WithMany("AppRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppRole");
                });

            modelBuilder.Entity("brgy_mgmt_dotnet.identity.Models.AppUserClaim", b =>
                {
                    b.HasOne("brgy_mgmt_dotnet.identity.Models.AppUser", "AppUser")
                        .WithMany("AppUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("brgy_mgmt_dotnet.identity.Models.AppUserRole", b =>
                {
                    b.HasOne("brgy_mgmt_dotnet.identity.Models.AppRole", "AppRole")
                        .WithMany("AppUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("brgy_mgmt_dotnet.identity.Models.AppUser", "AppUser")
                        .WithMany("AppUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppRole");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("brgy_mgmt_dotnet.identity.Models.AppRole", b =>
                {
                    b.Navigation("AppRoleClaims");

                    b.Navigation("AppUserRoles");
                });

            modelBuilder.Entity("brgy_mgmt_dotnet.identity.Models.AppUser", b =>
                {
                    b.Navigation("AppUserClaims");

                    b.Navigation("AppUserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
